import subprocess
from pathlib import Path
from time import perf_counter
from tempfile import NamedTemporaryFile


class NuXMVChecker:
    BASEFILE: Path
    BASECONTENT: str

    @classmethod
    def set_basefile(cls, path: Path):
        cls.BASEFILE = path
        ebmc_out = subprocess.check_output(["ebmc", cls.BASEFILE, "--smv-netlist"])
        ebmc_out_str = ebmc_out.decode().strip()
        cls.BASECONTENT = ebmc_out_str[ebmc_out_str.find("-- Generated by EBMC") :]

    @classmethod
    def check_spec(cls, nu_xmv_spec: str):
        print(f"Checking {nu_xmv_spec} with nuxmv\n")

        check_content = cls.BASECONTENT + "\n\n" + nu_xmv_spec

        with NamedTemporaryFile("w", suffix=".sv", delete=False) as f:
            f.write(check_content)
            fname = f.name

        start = perf_counter()
        subprocess.run(["nuXmv", fname], check=True)
        duration = perf_counter() - start

        print(f"Checked {nu_xmv_spec} with nuxmv in {duration} seconds")

    @classmethod
    def check_state_unreachable(
        cls, curr_vars: list[str], next_vars: list[str], non_state_vars: list[str]
    ):
        ltlspec = f"LTLSPEC G (({' & '.join(curr_vars + non_state_vars)}) & X ({' & '.join(next_vars)}))"
        cls.check_spec(ltlspec)


def bw_to_verlog(bw: str) -> str:
    # This works for Boolean states that are not indexed like Verilog.BLINK.cnt[0]
    # TODO: For those, I still have to figure out where the index lives
    assert bw.find("::") != -1
    prefixless = bw[bw.find("::") :].strip(":|")
    assert int(prefixless[-1]) == 1 or int(prefixless[-1]) == 2
    flag = "TRUE" if int(prefixless[-1]) == 2 else "FALSE"
    return f"Verilog.{prefixless[:-1]} = {flag}"
