import sys
import tempfile
import subprocess
from pathlib import Path
from itertools import chain

import bitwuzla

from nur.bitwuzla_utils import b_and, b_range


# TODO: Figure out how to read the other inputs from the file.
# I don't like having to specify things about a file not knowing
# how hard it is to figure it out from scratch when profiling.
def read_svfile(svfile: Path, module_name: str, bits: int):
    """
    This is a "parser" that converts to a bunch of other formats with ebmc and then reads those.
    It's far from pretty, and I would have presumed just writing a parser from scratch might be easier,
    but it works and I am not going to change it as I don't plan on touching it anyway.
    """
    smb_out = subprocess.check_output(
        ["ebmc", svfile, "--show-symbol-table", "--bound", "0", "--top", module_name]
    )
    state_vars, inp_out_vars = read_for_vars(smb_out.decode().strip())

    # No, removing `--outfile` does not make it output to stdout. I checked.
    with tempfile.NamedTemporaryFile(mode="r+") as tmp:
        subprocess.run(
            [
                "ebmc",
                svfile,
                "--smt2",
                "--bound",
                "1",
                "--top",
                module_name,
                "--outfile",
                tmp.name,
            ],
            check=True,
        )

        tmp.seek(0)
        smt_out = tmp.read()
    bw_obj, curr_vars, next_vars, non_state_vars, state_names = create_bitwuzla_model(
        module_name, state_vars, bits, inp_out_vars, smt_out.strip()
    )

    # TODO: Put all this in proper data structures such that it makes more sense what belongs to what
    return (
        state_vars,
        inp_out_vars,
        bw_obj,
        curr_vars,
        next_vars,
        non_state_vars,
        state_names,
    )


def read_for_vars(data: str):
    data = data[data.find("Symbols:") + 9 :]
    blocks = [block.strip() for block in data.strip().split("\n\n")]
    result = {}
    for block in blocks:
        lines = block.split("\n")
        var_name = lines[0].strip()
        var_info = {}
        for line in lines[1:]:
            if len(line.split(":", 1)) == 1:
                continue
            key, value = map(str.strip, line.split(":", 1))
            var_info[key] = value
        result[var_name] = var_info

    state_var, inp_out_vars = dict(), dict()
    for var in result.keys():
        if len(var.split(".", 1)) != 2:
            continue
        if var.split(".", 1)[1] == "clk":
            continue
        if result[var]["flags"].split()[0] in ["state_var", "input", "output"]:
            lb, ub, size, dist = 0, 1, 1, None
            if result[var]["type"] == "bool":
                dist = None
            if result[var]["type"] == "unsignedbv":
                size = int(result[var]["* width"])
                lb = 0
                ub = 2**size - 1
            if result[var]["flags"].split()[0] in ["input", "output"]:
                inp_out_vars[var.split(".", 1)[1]] = {
                    "lb": lb,
                    "ub": ub,
                    "size": size,
                    "dist": dist,
                    "type": result[var]["flags"].split()[0],
                }
            else:
                state_var[var.split(".", 1)[1]] = {
                    "lb": lb,
                    "ub": ub,
                    "size": size,
                    "dist": dist,
                    "type": "state",
                }
    return state_var, inp_out_vars


def create_bitwuzla_model(module_name, state_vars, bits, inp_out_vars, smt2_model):
    """
    take an smt_model generated by embc. clean and extend with NuR-prefixed
    declarations, parse into Bitwuzla. Assert range constraints if __debug__.

    Returns (bw_obj, curr_vars, next_vars, non_state_vars, state_names).
    """
    smt2_model = "\n".join(
        [
            line
            for line in smt2_model.split("\n")
            if not any(rem_str in line for rem_str in ["(exit)", "; end of SMT2 file"])
        ]
    )

    for key, value in chain(state_vars.items(), inp_out_vars.items()):
        pre_ = f"|Verilog::{module_name}.{key}@0|"
        curr_ = f"|Verilog::{module_name}.{key}@1|"
        next_ = f"|Verilog::{module_name}.{key}@2|"
        pre_bv = pre_ if value["size"] > 1 else f"(ite {pre_} (_ bv1 1) (_ bv0 1))"
        curr_bv = curr_ if value["size"] > 1 else f"(ite {curr_} (_ bv1 1) (_ bv0 1))"
        next_bv = next_ if value["size"] > 1 else f"(ite {next_} (_ bv1 1) (_ bv0 1))"
        pre_B = f"|NuR::{module_name}.{key}0|"
        curr_B = f"|NuR::{module_name}.{key}1|"
        next_B = f"|NuR::{module_name}.{key}2|"

        if value["type"] == "state":
            assert (
                (pre_ in smt2_model) and (curr_ in smt2_model) and (next_ in smt2_model)
            )
            smt2_0 = (
                f"(declare-const {pre_B } (_ BitVec {bits}))\n"
                f"(assert (= ((_ zero_extend {bits - value['size']}) {pre_bv }) {pre_B }))"
            )
            smt2_1 = (
                f"(declare-const {curr_B} (_ BitVec {bits}))\n"
                f"(assert (= ((_ zero_extend {bits - value['size']}) {curr_bv}) {curr_B}))"
            )
            smt2_2 = (
                f"(declare-const {next_B} (_ BitVec {bits}))\n"
                f"(assert (= ((_ zero_extend {bits - value['size']}) {next_bv}) {next_B}))"
            )
            smt2_model += "\n" + smt2_0 + "\n" + smt2_1 + "\n" + smt2_2

        elif value["type"] == "input":
            assert (pre_ in smt2_model) and (curr_ in smt2_model)
            smt2_0 = (
                f"(declare-const {pre_B } (_ BitVec {bits}))\n"
                f"(assert (= ((_ zero_extend {bits - value['size']}) {pre_bv }) {pre_B }))"
            )
            smt2_1 = (
                f"(declare-const {curr_B} (_ BitVec {bits}))\n"
                f"(assert (= ((_ zero_extend {bits - value['size']}) {curr_bv}) {curr_B}))"
            )
            smt2_model += "\n" + smt2_0 + "\n" + smt2_1

        elif value["type"] == "output":
            assert curr_ in smt2_model
            if next_ in smt2_model:
                smt2_1 = (
                    f"(declare-const {curr_B} (_ BitVec {bits}))\n"
                    f"(assert (= ((_ zero_extend {bits - value['size']}) {curr_bv}) {curr_B}))"
                )
                smt2_2 = (
                    f"(declare-const {next_B} (_ BitVec {bits}))\n"
                    f"(assert (= ((_ zero_extend {bits - value['size']}) {next_bv}) {next_B}))"
                )
                smt2_model += "\n" + smt2_1 + "\n" + smt2_2
            else:
                smt2_1 = (
                    f"(declare-const {curr_B} (_ BitVec {bits}))\n"
                    f"(assert (= ((_ zero_extend {bits - value['size']}) {curr_bv}) {curr_B}))"
                )
                smt2_model += "\n" + smt2_1
        else:
            print("[INVALID Value Type]")
            breakpoint()

    smt2_model = smt2_model.replace("(assert false)", "").replace("(check-sat)", "")
    curr_vars, next_vars, non_state_vars, state_names = [], [], [], []
    tm = bitwuzla.TermManager()
    opt = bitwuzla.Options()
    parser = bitwuzla.Parser(tm, opt)
    _res = parser.parse(smt2_model, parse_file=False)
    bvsizeB = tm.mk_bv_sort(bits)
    rangesC = []
    rangesN = []
    bw_obj = (tm, opt, parser, bvsizeB)
    for key, value in chain(state_vars.items(), inp_out_vars.items()):
        if value["type"] == "state":
            state_names.append(key)
            cv = parser.parse_term(f"|NuR::{module_name}.{key}1|")
            nv = parser.parse_term(f"|NuR::{module_name}.{key}2|")
            curr_vars.append(cv)
            next_vars.append(nv)
            rangesN.append(b_range(next_vars[-1], bw_obj, value["lb"], value["ub"]))
            rangesC.append(b_range(curr_vars[-1], bw_obj, value["lb"], value["ub"]))
        elif value["type"] == "input":
            cv = parser.parse_term(f"|NuR::{module_name}.{key}1|")
            non_state_vars.append(cv)
            rangesC.append(
                b_range(non_state_vars[-1], bw_obj, value["lb"], value["ub"])
            )
        elif value["type"] == "output":
            cv = parser.parse_term(f"|NuR::{module_name}.{key}1|")
            non_state_vars.append(cv)
            rangesC.append(
                b_range(non_state_vars[-1], bw_obj, value["lb"], value["ub"])
            )
    # 0101, 1212 -> 1_delay; 1211 -> s2_lcd
    if __debug__:
        # TODO: I am not quite sure this is indeed a debug-only check used only for checking correct parsing,
        # (as it would seem from the way it was written in the original code, setting up breakpoint() if not,)
        # or if there is a way to create a parsable sv file that fails this, requiring this to always run.
        assert_range_invariant(bw_obj, rangesC, rangesN, curr_vars, next_vars)
        parser.bitwuzla().assert_formula(b_and(rangesC, bw_obj))
        parser.bitwuzla().assert_formula(b_and(rangesN, bw_obj))
    bw_obj = (tm, opt, parser, bvsizeB)
    return bw_obj, curr_vars, next_vars, non_state_vars, state_names


def assert_range_invariant(bw_obj, rangesC, rangesN, curr_vars, next_vars):
    """Verify that current-state ranges imply next-state ranges (range invariant)."""
    # The variable range needs to be an invariant, which means if current state satisfies range so should next state.
    tm, _opt, parser, _bvsizeB = bw_obj

    parser.bitwuzla().push()
    parser.bitwuzla().assert_formula(b_and(rangesC, bw_obj))
    parser.bitwuzla().assert_formula(
        tm.mk_term(bitwuzla.Kind.NOT, [b_and(rangesN, bw_obj)])
    )
    res = parser.bitwuzla().check_sat()
    if res == bitwuzla.Result.SAT:
        from nur.bitwuzla_utils import bitwuzla_print

        print("Range invariant failed. Printing debug info:", file=sys.stderr)
        bitwuzla_print(curr_vars, bw_obj, file=sys.stderr)
        bitwuzla_print(next_vars, bw_obj, file=sys.stderr)
        raise AssertionError("Current-state ranges must imply next-state ranges")
    parser.bitwuzla().pop()
